// ═══════════════════════════════════════════════════════════════
//  Offer Catalog — все возможные AI-предложения по уровням
// ═══════════════════════════════════════════════════════════════
import type { AIEvent } from './types'

type OfferTemplate = Omit<AIEvent, 'kind' | 'id' | 'startTs' | 'endTs'>

export const OFFER_CATALOG: OfferTemplate[] = [
  // ── Level 1: Уют ──────────────────────────────────────────
  {
    title: 'Прогулка с собакой',
    emoji: '🐕',
    category: 'nature',
    boldnessRequired: 1,
    costType: 'solo',
    minAgeGroup: 'young',
    allowedHours: [7, 21],
    durationMin: 30,
    color: '#e8f5e9',
    description: 'Свежий воздух и движение — лучший перезапуск',
  },
  {
    title: 'Медитация',
    emoji: '🧘',
    category: 'relaxation',
    boldnessRequired: 1,
    costType: 'solo',
    minAgeGroup: 'young',
    allowedHours: [6, 23],
    durationMin: 20,
    color: '#f3e5f5',
    description: '10 минут тишины перезаряжают лучше кофе',
  },
  {
    title: 'Полив сада / растений',
    emoji: '🌿',
    category: 'nature',
    boldnessRequired: 1,
    costType: 'solo',
    minAgeGroup: 'young',
    allowedHours: [7, 20],
    durationMin: 15,
    color: '#e8f5e9',
    description: 'Забота о живом — лучший антистресс',
  },
  {
    title: 'Скандинавская ходьба',
    emoji: '🚶',
    category: 'fitness',
    boldnessRequired: 1,
    costType: 'solo',
    minAgeGroup: 'senior',
    allowedHours: [8, 19],
    durationMin: 40,
    color: '#fff3e0',
    description: 'Мягкая нагрузка для суставов и сердца',
  },
  {
    title: 'Чтение книги',
    emoji: '📖',
    category: 'relaxation',
    boldnessRequired: 1,
    costType: 'solo',
    minAgeGroup: 'young',
    allowedHours: [6, 24],
    durationMin: 45,
    color: '#fff8e1',
    description: 'Лучший способ отключиться от экранов',
  },
  {
    title: 'Звонок близкому человеку',
    emoji: '📞',
    category: 'family',
    boldnessRequired: 1,
    costType: 'solo',
    minAgeGroup: 'young',
    allowedHours: [9, 21],
    durationMin: 20,
    color: '#fce4ec',
    description: 'Поддержи связь с теми, кто важен',
  },

  // ── Level 2: Стандарт ─────────────────────────────────────
  {
    title: 'Выставка в галерее',
    emoji: '🎨',
    category: 'culture',
    boldnessRequired: 2,
    costType: 'external',
    minAgeGroup: 'young',
    allowedHours: [10, 20],
    durationMin: 90,
    color: '#fff8e1',
    description: 'Новые впечатления без лишних усилий',
  },
  {
    title: 'Кофейня с ноутбуком',
    emoji: '☕',
    category: 'food',
    boldnessRequired: 2,
    costType: 'external',
    minAgeGroup: 'young',
    allowedHours: [8, 22],
    durationMin: 60,
    color: '#fbe9e7',
    description: 'Смена обстановки — лучший буст продуктивности',
  },
  {
    title: 'Подтягивания на турнике',
    emoji: '💪',
    category: 'fitness',
    boldnessRequired: 2,
    costType: 'solo',
    minAgeGroup: 'young',
    allowedHours: [7, 21],
    durationMin: 20,
    color: '#fce4ec',
    description: 'Быстрая тренировка без зала',
  },
  {
    title: 'Поход в кино',
    emoji: '🎬',
    category: 'culture',
    boldnessRequired: 2,
    costType: 'external',
    minAgeGroup: 'young',
    allowedHours: [12, 23],
    durationMin: 120,
    color: '#e8eaf6',
    description: 'Отличный способ переключиться',
  },
  {
    title: 'Велопрогулка',
    emoji: '🚴',
    category: 'fitness',
    boldnessRequired: 2,
    costType: 'solo',
    minAgeGroup: 'young',
    allowedHours: [8, 20],
    durationMin: 60,
    color: '#fff3e0',
    description: 'Город совсем другой с велосипеда',
  },
  {
    title: 'Новый ресторан',
    emoji: '🍽️',
    category: 'food',
    boldnessRequired: 2,
    costType: 'external',
    minAgeGroup: 'young',
    allowedHours: [12, 22],
    durationMin: 75,
    color: '#fbe9e7',
    description: 'Маленькое гастрономическое приключение',
  },

  // ── Level 3: Эксперимент ──────────────────────────────────
  {
    title: 'Быстрые свидания',
    emoji: '💘',
    category: 'social',
    boldnessRequired: 3,
    costType: 'external',
    minAgeGroup: 'young',
    allowedHours: [18, 23],
    durationMin: 120,
    color: '#fce4ec',
    description: 'Познакомься с 10 людьми за вечер',
  },
  {
    title: 'Квиз в баре',
    emoji: '🧠',
    category: 'social',
    boldnessRequired: 3,
    costType: 'external',
    minAgeGroup: 'young',
    allowedHours: [18, 24],
    durationMin: 120,
    color: '#e8eaf6',
    description: 'Командная игра — лучший нетворкинг',
  },
  {
    title: 'Стендап-комедия',
    emoji: '🎤',
    category: 'culture',
    boldnessRequired: 3,
    costType: 'external',
    minAgeGroup: 'young',
    allowedHours: [19, 24],
    durationMin: 90,
    color: '#fff8e1',
    description: 'Смех — лучшая терапия',
  },
  {
    title: 'Импровизационный театр',
    emoji: '🎭',
    category: 'culture',
    boldnessRequired: 3,
    costType: 'external',
    minAgeGroup: 'young',
    allowedHours: [18, 23],
    durationMin: 90,
    color: '#e0f2f1',
    description: 'Выйди из зоны комфорта на сцене',
  },
  {
    title: 'Ночной рынок',
    emoji: '🌙',
    category: 'social',
    boldnessRequired: 3,
    costType: 'external',
    minAgeGroup: 'young',
    allowedHours: [19, 24],
    durationMin: 90,
    color: '#e8eaf6',
    description: 'Атмосфера, еда, люди',
  },

  // ── Level 4: Без границ ───────────────────────────────────
  {
    title: 'Ночной клуб',
    emoji: '🎉',
    category: 'nightlife',
    boldnessRequired: 4,
    costType: 'external',
    minAgeGroup: 'young',
    allowedHours: [22, 6],
    durationMin: 180,
    color: '#1a1a2e',
    description: 'Танцы до рассвета',
  },
  {
    title: 'Массажный салон',
    emoji: '💆',
    category: 'adult',
    boldnessRequired: 4,
    costType: 'external',
    minAgeGroup: 'adult',
    allowedHours: [10, 23],
    durationMin: 60,
    color: '#3d1a4a',
    description: 'Расслабление без ограничений',
  },
  {
    title: 'Стриптиз-клуб',
    emoji: '🔞',
    category: '18+',
    boldnessRequired: 4,
    costType: 'external',
    minAgeGroup: 'adult',
    allowedHours: [21, 5],
    durationMin: 120,
    color: '#1a0a0a',
    description: 'Только для взрослых',
  },
  {
    title: 'Личное время (18+)',
    emoji: '🔒',
    category: 'intimate',
    boldnessRequired: 4,
    costType: 'solo',
    minAgeGroup: 'adult',
    allowedHours: [0, 24],
    durationMin: 30,
    color: '#2d1b33',
    description: 'Твоё личное пространство',
  },
]
